config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: "users#index"
    resources :songs
    resources :categories
    resources :users
    resources :albums
    resources :artists
  end
  get "/search", to: "searchs#search"
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :albums, dependent: :destroy

  scope :order_name, ->{order created_at: :desc}
  scope :search_by_name, ->search do
    select(:id, :name).where "name LIKE ?", "%#{search}%"
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :load_category, only: [:update, :edit, :destroy]

  def index
    @categories = Category.order_name.search_by_name(params[:search])
      .page(params[:page]).per Setting.paginate.page
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params

    if @category.save
      flash[:success] = t "controller.admin.users.sc_category"
    else
      flash[:error] = t "controller.admin.users.fail_category"
    end
    respond_to do |format|
      format.html redirect_to admin_categories_path
      format.js
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "controller.admin.users.ud_category"
      redirect_to admin_categories_path
    else
      flash[:error] = t "controller.admin.users.fail_ud_category"
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "controller.admin.users.del_category"
    else
      flash[:error] = t "controller.admin.users.fail_del_category"
    end
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit :name
  end

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category
    flash[:error] = t "controller.admin.users.load_category"
    redirect_to admin_categories_path
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= category.name %></td>
  <td><%= category.created_at.strftime format: :date_month_year_concise %></td>
  <td>
    <%= link_to edit_admin_category_path(category) do %>
      <span><i class="fa fa-edit fa-1px"></i></span>
    <% end %>
  </td>
  <td>
    <%= link_to admin_category_path(category), method: :delete, data: {confirm: t("flash.danger")} do %>
      <span><i class="fa fa-times fa-1px"></i></span>
    <% end %>
  </td>
</tr>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <div class="register-top-grid">
    <%= render "shared/error_messages", object: f.object %>
    <div class="mation">
      <span><%= t "garena.name2" %></span>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="register-but">
      <%= f.submit :Submit, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<div class="clearfix"> </div>

app/views/admin/categories/create.js.erb
$('#exampleModal1 .close').click();
$('.category-selection').html("<%= j render 'admin/albums/select-category' %>");
$("#exampleModal1").modal("hide")

app/views/admin/categories/edit.html.erb
<div class="modal-header">
  <h3><%= t "views.admin.categories.edit.title" %></h3>
</div>
<%= render "form" %>

app/views/admin/categories/index.html.erb
<div class="container-fluid">
  <div class="row">
    <h3 class="sub-header"><%= t "views.admin.categories.index.category_list" %></h3>
    <%= form_tag(admin_categories_path, method: :get) do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag t("garena.search"), name: nil %>
    <% end %><br/>
    <%= link_to t("garena.excel"), admin_categories_path(format: "xls"), class: "pull-right" %>
    <%= link_to new_admin_category_path do %>
      <span><i class="fa fa-plus fa-2px"></i><%= t "views.admin.categories.index.new_category" %></span>
    <% end %>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
        <tr>
          <th><%= t "garena.name" %></th>
          <th><%= t "garena.create_at" %></th>
          <th><%= t "garena.edit" %></th>
          <th><%= t "garena.delete" %></th>
        </tr>
        </thead>
        <tbody>
        <%= render partial: "category", collection: @categories %>
        </tbody>
      </table>
      <%= paginate @categories, theme: "twitter-bootstrap-3" %>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="modal-header">
  <h3><%= t "views.admin.categories.edit.new_category" %></h3>
</div>
<%= render "form" %>