config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: "users#index"
    resources :songs
    resources :categories
    resources :users
    resources :albums
    resources :artists
  end
  get "/search", to: "searchs#search"
end

app/views/admin/layouts/_header.html.erb
<nav class= "navbar navbar-inverse navbar-fixed-top">
  <div class= "container-fluid">
    <div class= "navbar-header">
      <button type= "button" class= "navbar-toggle collapsed" data-toggle= "collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t("views.admin.layouts.header.logo"), admin_root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a><%= t("views.admin.layouts.header.hello") %></a>
        </li>
        <li>
          <%= link_to t("views.admin.layouts.header.profile"), current_user %>
        </li>
        <li>
          <%= link_to logout_path, method: :delete do %>
            <span><i class="fa fa-sign-out fa-1x"></i></span>
            <%= t "views.admin.layouts.header.log_out" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/admin/layouts/_sidebar.html.erb
<ul class="nav nav-sidebar">
  <li>
    <%= link_to t("views.admin.layouts.sidebar.user"), admin_users_path %>
  </li>
  <li>
    <%= link_to t("views.admin.layouts.sidebar.category"), admin_categories_path %>
  </li>
  <li>
    <%= link_to t("views.admin.layouts.sidebar.artists"), admin_artists_path %>
  </li>
  <li>
    <%= link_to t("views.admin.layouts.sidebar.album"), admin_albums_path %>
  </li>
  <li>
    <%= link_to t("views.admin.layouts.sidebar.song"), admin_songs_path %>
  </li>
</ul>

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t("views.admin.layouts.application.admin") %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
</head>

<body>
<%= render "admin/layouts/header" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2 sidebar fix-sidebar">
      <%= render "admin/layouts/sidebar" %>
    </div>
    <div class="col-md-10 main fix-sidebar">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>