config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: "users#index"
    resources :songs
    resources :categories
    resources :users
    resources :albums
    resources :artists
  end
  get "/search", to: "searchs#search"
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token

  enum role: [:user, :admin]

  before_save :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: {maximum: Settings.user.maximum_name}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
  length: {maximum: Settings.user.maximum_email},
  format: {with: VALID_EMAIL_REGEX},
  uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true,
  length: {minimum: Settings.user.minimum_password}, allow_nil: true

  has_many :comments, dependent: :destroy
  has_many :favorite_lists, dependent: :destroy
  has_many :lyrics, dependent: :destroy
  has_many :ratings, dependent: :destroy

  scope :order_user, ->{order created_at: :desc}
  scope :search_by_name, ->search do
    select(:id, :name, :email, :role, :created_at, :activated)
      .where "name LIKE ? OR email LIKE ?", "%#{search}%", "%#{search}%"
  end

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? attribute, token
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new digest.is_password? token
  end

  def forget
    update_attributes remember_digest: nil
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attributes(reset_digest: User.digest(reset_token),
      reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < Setting.time.hours.ago
  end

  class << self
    def digest string
      if ActiveModel::SecurePassword.min_cost
        cost = BCrypt::Engine::MIN_COST
      else
        cost = BCrypt::Engine.cost
      end
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end

    def from_omniauth auth
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.uid = auth.uid
        user.email = auth.info.email
        user.name = auth.info.name
        user.activated = true
        user.password_digest = auth.credentials.token
        user.activation_digest = auth.credentials.token
        user.activated_at = Time.now
      end
    end

    def new_with_session params
      if session["user_attributes"]
        new(session["user_attributes"]) do |user|
          user.attributes = params
          user.valid?
        end
      else
        super
      end
    end
  end

  private

  def downcase_email
    self.email = email.downcase!
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :load_user, only: [:edit, :update, :destroy]

  def index
    @users = User.order_user.search_by_name(params[:search])
      .page(params[:page]).per Setting.paginate.page
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "controller.admin.users.sc_user"
    else
      flash[:danger] = t "controller.admin.users.fail_user"
      render :new
    end
    redirect_to admin_users_path
  end

  def edit
  end

  def update
    activated = params[:user][:activated] == "0" ? false : true
    update_activated activated
    if @user.update_attributes user_params
      flash[:success] = t "controller.admin.users.ud_user"
      redirect_to admin_users_path
    else
      flash[:error] = t "controller.admin.users.fail_ud_user"
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t "controller.admin.users.del_user"
    else
      flash[:error] = t "controller.admin.users.fail_del_user"
    end
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end

  def activated?
    @user.update_attributes activated: activated
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:error] = t "controller.admin.users.load_user"
    redirect_to admin_users_path
  end
end

app/helpers/user_helper.rb
module UserHelper
  def activate_user user
    if user.activated?
      t("garena.activated")
    else
      t("garena.not_activated")
    end
  end

  def admin_user user
    if user.admin?
      t("views.admin.users.user.admin")
    else
      t("views.admin.users.user.member")
    end
  end
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <div class="register-top-grid">
    <br/>
    <h3><%= t "views.admin.users.form.info" %></h3>
    <%= render "shared/error_messages", object: f.object %>
    <div class="mation">
      <span><%= t "views.admin.users.form.name" %></span>
      <%= f.text_field :name, class: "form-control" %>

      <span><%= t "views.admin.users.form.email" %></span>
      <%= f.email_field :email, class: "form-control" %>
    </div>
    <div class="register-bottom-grid">
      <div class="mation">
        <span><%= t "views.admin.users.form.password" %></span>
        <%= f.password_field :password, class: "form-control" %><br/>
        <span><%= t "views.admin.users.form.password_cf" %></span>
        <%= f.password_field :password_confirmation, class: "form-control" %><br/>
        <%= f.label :activated, class: "check_box inline" do %>
          <%= f.check_box :activated %>
          <span><%= t "garena.activated" %></span>
        <% end %>
      </div>
    </div>
    <div class="register-but">
      <%= f.submit :Submit, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<div class="clearfix"> </div>

app/views/admin/users/_user.html.erb
<tr>
  <td><%= link_to user.name, user_path(user) %></td>
  <td><%= user.email %></td>
  <td><%= activate_user user %></td>
  <td><%= user.created_at.strftime format: :date_month_year_concise %></td>
  <td>
    <%= admin_user user %>
  </td>
  <% if unless user.admin? %>
    <td>
      <%= link_to edit_admin_user_path(user) do %>
        <span><i class="fa fa-edit fa-1px"></i></span>
      <% end %>
    </td>
    <td>
      <%= link_to admin_user_path(user), method: :delete, data: {confirm: t("flash.danger")} do %>
        <span><i class="fa fa-times fa-1px"></i></span>
      <% end %>
    </td>
  <% end %>
  <% end %>
</tr>

app/views/admin/users/edit.html.erb
<%= render "form" %>

app/views/admin/users/index.html.erb
<div class="container-fluid">
 <div class="row">
  <h3 class="sub-header"><%= t "views.admin.users.index.user_list" %></h3>
   <%= form_tag admin_users_path, method: :get do %>
     <%= text_field_tag :search, params[:search] %>
     <%= submit_tag t("garena.search"), name: nil %>
   <% end %>
    <%= link_to t("garena.excel"), admin_users_path(format: "xls"), class: "pull-right" %>
    <%= link_to new_admin_user_path do %>
      <span><i class="fa fa-plus fa-2px"></i><%= t "views.admin.users.index.new_user" %></span>
    <% end %>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= t "garena.name" %></th>
            <th><%= t "garena.email" %></th>
            <th><%= t "garena.activated" %></th>
            <th><%= t "garena.create_at" %></th>
            <th><%= t "garena.role" %></th>
            <th><%= t "garena.edit" %></th>
            <th><%= t "garena.delete" %></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: "user", collection: @users %>
        </tbody>
      </table>
      <%= paginate @users, theme: "twitter-bootstrap-3" %>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<%= render "form" %>